apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xen-pool-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 24h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        root-pass: "{{ .password }}"
  dataFrom:
    - extract:
        # value set by vars/vault.secrets.yml
        # (encrypted) in homelab-k8s project:
        # https://github.com/erhhung/homelab-k8s
        key: kv-prod/xcp-ng/root-user
