apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - externalsecret.yaml
namespace: xen-exporter

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: xen-exporter

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches
patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
  - path: patches/servicemonitor.yaml
    target:
      kind: ServiceMonitor
