apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xen-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xen-exporter
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
