apiVersion: v1
kind: Service
metadata:
  name: xen-exporter
spec:
  selector:
    app.kubernetes.io/name: xen-exporter
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
